import type { OpeningOptionDefinition } from "./openingOptionsTypes";

export const OPENING_OPTION_REGISTRY: OpeningOptionDefinition[] = [
  {
    id: "mood-calm",
    family: "mood",
    label: "宁静",
    parameterDelta: {
      impression: { calm: 0.82, warmth: 0.48, softness: 0.66, energy: 0.22, luxury: 0.3 },
      color: { saturation: 0.28, contrast: 0.3, visibility: 0.34 },
      patternIntent: { complexity: 0.32 },
      arrangement: { openness: 0.62, density: 0.38, flow: 0.52, order: 0.5 },
      presence: { blending: 0.72, focalness: 0.24, visualWeight: 0.35 },
    },
    suggestedNextTargets: ["space", "patternIntent"],
  },
  {
    id: "mood-warm",
    family: "mood",
    label: "温暖",
    parameterDelta: {
      impression: { calm: 0.58, warmth: 0.84, softness: 0.7, energy: 0.34, luxury: 0.36 },
      color: { warmth: 0.78, saturation: 0.44, contrast: 0.36, visibility: 0.42 },
      presence: { blending: 0.64, focalness: 0.3, visualWeight: 0.4 },
    },
    suggestedNextTargets: ["space", "color"],
  },
  {
    id: "mood-free",
    family: "mood",
    label: "自由",
    parameterDelta: {
      impression: { calm: 0.46, warmth: 0.46, softness: 0.5, energy: 0.54, luxury: 0.2 },
      arrangement: { openness: 0.78, density: 0.28, flow: 0.76, order: 0.24 },
      patternIntent: { organic: 0.7, geometry: 0.2, complexity: 0.46 },
      presence: { blending: 0.48, focalness: 0.42, visualWeight: 0.38 },
    },
    suggestedNextTargets: ["patternIntent", "presence"],
  },
  {
    id: "mood-energetic",
    family: "mood",
    label: "有活力",
    parameterDelta: {
      impression: { calm: 0.18, warmth: 0.52, softness: 0.3, energy: 0.84, luxury: 0.28 },
      color: { saturation: 0.72, contrast: 0.68, visibility: 0.72 },
      patternIntent: { complexity: 0.58, motifPresence: 0.66 },
      presence: { blending: 0.28, focalness: 0.76, visualWeight: 0.7 },
    },
    suggestedNextTargets: ["presence", "patternIntent"],
  },
  {
    id: "mood-restrained",
    family: "mood",
    label: "克制",
    parameterDelta: {
      impression: { calm: 0.74, warmth: 0.42, softness: 0.48, energy: 0.2, luxury: 0.34 },
      color: { saturation: 0.2, contrast: 0.26, visibility: 0.22 },
      patternIntent: { complexity: 0.28, motifPresence: 0.24 },
      presence: { blending: 0.8, focalness: 0.18, visualWeight: 0.26 },
    },
    suggestedNextTargets: ["presence", "color"],
  },
  {
    id: "mood-natural",
    family: "mood",
    label: "自然",
    parameterDelta: {
      impression: { calm: 0.66, warmth: 0.56, softness: 0.6, energy: 0.34, luxury: 0.18 },
      patternIntent: { organic: 0.82, geometry: 0.18, abstraction: 0.56, complexity: 0.44 },
      color: { warmth: 0.58, saturation: 0.34, visibility: 0.4 },
      arrangement: { flow: 0.68, openness: 0.58 },
    },
    suggestedNextTargets: ["patternIntent", "space"],
  },
  {
    id: "mood-relaxed",
    family: "mood",
    label: "松弛",
    parameterDelta: {
      impression: { calm: 0.78, warmth: 0.54, softness: 0.74, energy: 0.2, luxury: 0.18 },
      arrangement: { openness: 0.7, density: 0.26, flow: 0.58, order: 0.36 },
      presence: { blending: 0.72, focalness: 0.22, visualWeight: 0.3 },
    },
    suggestedNextTargets: ["space", "presence"],
  },
  {
    id: "mood-luxury",
    family: "mood",
    label: "精致 / 奢雅",
    parameterDelta: {
      impression: { calm: 0.36, warmth: 0.58, softness: 0.52, energy: 0.48, luxury: 0.88 },
      color: { contrast: 0.62, saturation: 0.54, visibility: 0.66 },
      arrangement: { order: 0.72, density: 0.64 },
      presence: { blending: 0.24, focalness: 0.8, visualWeight: 0.78 },
    },
    suggestedNextTargets: ["space", "presence"],
  },
  {
    id: "space-living-room",
    family: "space",
    label: "客厅 / 居家公共区域",
    parameterDelta: {
      space: { domestic: 0.88, hospitality: 0.22, officeLike: 0.08, resting: 0.46, social: 0.72 },
      presence: { blending: 0.5, focalness: 0.52, visualWeight: 0.5 },
    },
    suggestedNextTargets: ["presence", "impression"],
  },
  {
    id: "space-bedroom",
    family: "space",
    label: "卧室",
    parameterDelta: {
      space: { domestic: 0.9, hospitality: 0.1, officeLike: 0.06, resting: 0.88, social: 0.16 },
      impression: { calm: 0.82, softness: 0.74, warmth: 0.6 },
      patternIntent: { complexity: 0.24 },
      presence: { blending: 0.74, focalness: 0.2, visualWeight: 0.28 },
    },
    suggestedNextTargets: ["impression", "patternIntent"],
  },
  {
    id: "space-study",
    family: "space",
    label: "书房",
    parameterDelta: {
      space: { domestic: 0.72, hospitality: 0.12, officeLike: 0.42, resting: 0.52, social: 0.18 },
      impression: { calm: 0.74 },
      arrangement: { order: 0.66 },
      patternIntent: { complexity: 0.24, geometry: 0.42, organic: 0.4 },
    },
    suggestedNextTargets: ["patternIntent", "presence"],
  },
  {
    id: "space-kids-room",
    family: "space",
    label: "儿童房",
    parameterDelta: {
      space: { domestic: 0.88, hospitality: 0.1, officeLike: 0.04, resting: 0.64, social: 0.44 },
      color: { saturation: 0.62, visibility: 0.68 },
      patternIntent: { figurativeness: 0.56, complexity: 0.52, motifPresence: 0.7 },
      presence: { focalness: 0.58 },
    },
    suggestedNextTargets: ["patternIntent", "color"],
  },
  {
    id: "space-office",
    family: "space",
    label: "办公室",
    parameterDelta: {
      space: { domestic: 0.1, hospitality: 0.18, officeLike: 0.92, resting: 0.18, social: 0.36 },
      arrangement: { order: 0.72, openness: 0.42, density: 0.48 },
      patternIntent: { complexity: 0.26, geometry: 0.56 },
      presence: { blending: 0.72, focalness: 0.2, visualWeight: 0.32 },
    },
    suggestedNextTargets: ["impression", "patternIntent"],
  },
  {
    id: "space-hospitality",
    family: "space",
    label: "酒店 / 大堂 / 民宿",
    parameterDelta: {
      space: { domestic: 0.22, hospitality: 0.92, officeLike: 0.16, resting: 0.42, social: 0.8 },
      impression: { luxury: 0.72, calm: 0.42, energy: 0.48 },
      arrangement: { order: 0.68, density: 0.62 },
      presence: { blending: 0.3, focalness: 0.76, visualWeight: 0.74 },
    },
    suggestedNextTargets: ["presence", "patternIntent"],
  },
  {
    id: "space-undecided",
    family: "space",
    label: "还没确定",
    parameterDelta: {
      space: { domestic: 0.4, hospitality: 0.3, officeLike: 0.2, resting: 0.3, social: 0.3 },
    },
    suggestedNextTargets: ["impression", "patternIntent"],
  },
  {
    id: "pattern-botanical-soft",
    family: "pattern-style",
    label: "柔和叶片 / 植物纹理",
    parameterDelta: {
      patternIntent: {
        figurativeness: 0.42,
        abstraction: 0.62,
        organic: 0.84,
        geometry: 0.12,
        complexity: 0.34,
        motifPresence: 0.52,
      },
      arrangement: { flow: 0.68, openness: 0.54 },
      impression: { softness: 0.66, calm: 0.6 },
    },
    suggestedNextTargets: ["impression", "presence"],
  },
  {
    id: "pattern-landscape-abstract",
    family: "pattern-style",
    label: "抽象山水 / 地貌流线",
    parameterDelta: {
      patternIntent: {
        figurativeness: 0.2,
        abstraction: 0.82,
        organic: 0.7,
        geometry: 0.18,
        complexity: 0.46,
        motifPresence: 0.44,
      },
      arrangement: { flow: 0.78, openness: 0.56, density: 0.44 },
      impression: { calm: 0.64, luxury: 0.24 },
    },
    suggestedNextTargets: ["impression", "space"],
  },
  {
    id: "pattern-floral-accent",
    family: "pattern-style",
    label: "花卉点缀 / 花叶意向",
    parameterDelta: {
      patternIntent: {
        figurativeness: 0.54,
        abstraction: 0.46,
        organic: 0.78,
        geometry: 0.1,
        complexity: 0.5,
        motifPresence: 0.7,
      },
      presence: { focalness: 0.52 },
    },
    suggestedNextTargets: ["patternIntent", "presence"],
  },
  {
    id: "pattern-geometric-structured",
    family: "pattern-style",
    label: "几何拼块 / 线面构成",
    parameterDelta: {
      patternIntent: {
        figurativeness: 0.08,
        abstraction: 0.84,
        organic: 0.12,
        geometry: 0.88,
        complexity: 0.42,
        motifPresence: 0.58,
      },
      arrangement: { order: 0.78, openness: 0.42 },
      impression: { softness: 0.18, luxury: 0.26 },
    },
    suggestedNextTargets: ["presence", "space"],
  },
  {
    id: "pattern-texture-only",
    family: "pattern-style",
    label: "织物肌理 / 没有明显图案",
    parameterDelta: {
      patternIntent: {
        figurativeness: 0.04,
        abstraction: 0.72,
        organic: 0.5,
        geometry: 0.3,
        complexity: 0.2,
        motifPresence: 0.16,
      },
      presence: { blending: 0.8, focalness: 0.14, visualWeight: 0.24 },
    },
    suggestedNextTargets: ["presence", "impression"],
  },
  {
    id: "pattern-fluid-wave-cloud",
    family: "pattern-style",
    label: "波纹 / 云气 / 水意流动",
    parameterDelta: {
      patternIntent: {
        figurativeness: 0.16,
        abstraction: 0.78,
        organic: 0.74,
        geometry: 0.14,
        complexity: 0.38,
        motifPresence: 0.46,
      },
      arrangement: { flow: 0.88, openness: 0.6 },
      impression: { calm: 0.58, softness: 0.6 },
    },
    suggestedNextTargets: ["impression", "space"],
  },
  {
    id: "pattern-undecided",
    family: "pattern-style",
    label: "还不确定",
    parameterDelta: {
      patternIntent: {
        figurativeness: 0.3,
        abstraction: 0.4,
        organic: 0.4,
        geometry: 0.3,
        complexity: 0.3,
        motifPresence: 0.3,
      },
    },
    suggestedNextTargets: ["impression", "space"],
  },
  {
    id: "presence-blended",
    family: "presence",
    label: "与整体融合",
    parameterDelta: {
      presence: { blending: 0.86, focalness: 0.1, visualWeight: 0.2 },
      color: { visibility: 0.24, contrast: 0.2, saturation: 0.26 },
      patternIntent: { motifPresence: 0.2 },
    },
    suggestedNextTargets: ["color", "patternIntent"],
  },
  {
    id: "presence-soft-focal",
    family: "presence",
    label: "稍微跳出来",
    parameterDelta: {
      presence: { blending: 0.26, focalness: 0.74, visualWeight: 0.7 },
      color: { visibility: 0.68, contrast: 0.62, saturation: 0.56 },
      patternIntent: { motifPresence: 0.62 },
    },
    suggestedNextTargets: ["color", "patternIntent"],
  },
  {
    id: "presence-balanced",
    family: "presence",
    label: "能被注意到，但不要太抢",
    parameterDelta: {
      presence: { blending: 0.48, focalness: 0.52, visualWeight: 0.48 },
      color: { visibility: 0.46, contrast: 0.42, saturation: 0.38 },
      patternIntent: { motifPresence: 0.44 },
    },
    suggestedNextTargets: ["color", "patternIntent"],
  },
];

export const OPENING_OPTION_INDEX = new Map(OPENING_OPTION_REGISTRY.map((option) => [option.id, option]));
