import type { AnnotatedAssetRecord } from "./types";

/**
 * Batch 2 simplified pre-annotations for extended assets.
 * Selected for branch-representativeness rather than uniform coverage.
 */
export const extendedPreannotationsBatch2: AnnotatedAssetRecord[] = [
  { imageId: "071_545.jpg", title: "545", imageUrl: "/products-extra-fixed/071_545.jpg", annotation: { imageId: "071_545.jpg", firstOrder: { color: { warmth: 0.4, saturation: 0.1, lightness: 0.75 }, motif: { geometry: 0.0, organic: 1.0, complexity: 0.1 }, arrangement: { order: 0.3, spacing: 0.9, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "plush mauve-gray" }, tags: ["extended", "batch-2"] },
  { imageId: "072_546.png", title: "546", imageUrl: "/products-extra-fixed/072_546.png", annotation: { imageId: "072_546.png", firstOrder: { color: { warmth: 0.3, saturation: 0.1, lightness: 0.3 }, motif: { geometry: 0.2, organic: 0.8, complexity: 0.5 }, arrangement: { order: 0.4, spacing: 0.6, direction: 0.9 } }, annotationSource: "assisted", confidence: "low", notes: "heathered streaks" }, tags: ["extended", "batch-2"] },
  { imageId: "073_547.png", title: "547", imageUrl: "/products-extra-fixed/073_547.png", annotation: { imageId: "073_547.png", firstOrder: { color: { warmth: 0.5, saturation: 0.15, lightness: 0.6 }, motif: { geometry: 0.5, organic: 0.5, complexity: 0.3 }, arrangement: { order: 0.5, spacing: 0.7, direction: 0.5 } }, annotationSource: "assisted", confidence: "low", notes: "crosshatch linen" }, tags: ["extended", "batch-2"] },
  { imageId: "074_548.png", title: "548", imageUrl: "/products-extra-fixed/074_548.png", annotation: { imageId: "074_548.png", firstOrder: { color: { warmth: 0.7, saturation: 0.2, lightness: 0.6 }, motif: { geometry: 0.7, organic: 0.1, complexity: 0.2 }, arrangement: { order: 0.8, spacing: 0.9, direction: 0.9 } }, annotationSource: "assisted", confidence: "low", notes: "tan stripes bordered" }, tags: ["extended", "batch-2"] },
  { imageId: "075_549.jpg", title: "549", imageUrl: "/products-extra-fixed/075_549.jpg", annotation: { imageId: "075_549.jpg", firstOrder: { color: { warmth: 0.2, saturation: 0.25, lightness: 0.6 }, motif: { geometry: 0.6, organic: 0.1, complexity: 0.15 }, arrangement: { order: 0.7, spacing: 0.95, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "seafoam fine-grid" }, tags: ["extended", "batch-2"] },
  { imageId: "076_550.jpg", title: "550", imageUrl: "/products-extra-fixed/076_550.jpg", annotation: { imageId: "076_550.jpg", firstOrder: { color: { warmth: 0.5, saturation: 0.1, lightness: 0.7 }, motif: { geometry: 0.0, organic: 1.0, complexity: 0.05 }, arrangement: { order: 0.2, spacing: 0.95, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "sage plush solid" }, tags: ["extended", "batch-2"] },
  { imageId: "077_553.jpg", title: "553", imageUrl: "/products-extra-fixed/077_553.jpg", annotation: { imageId: "077_553.jpg", firstOrder: { color: { warmth: 0.15, saturation: 0.85, lightness: 0.5 }, motif: { geometry: 0.9, organic: 0.7, complexity: 0.6 }, arrangement: { order: 0.7, spacing: 0.4, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "teal circles bold" }, tags: ["extended", "batch-2"] },
  { imageId: "078_554.jpg", title: "554", imageUrl: "/products-extra-fixed/078_554.jpg", annotation: { imageId: "078_554.jpg", firstOrder: { color: { warmth: 0.2, saturation: 0.8, lightness: 0.35 }, motif: { geometry: 0.5, organic: 0.1, complexity: 0.2 }, arrangement: { order: 0.9, spacing: 0.95, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "emerald weave fringe" }, tags: ["extended", "batch-2"] },
  { imageId: "079_555.jpg", title: "555", imageUrl: "/products-extra-fixed/079_555.jpg", annotation: { imageId: "079_555.jpg", firstOrder: { color: { warmth: 0.25, saturation: 0.7, lightness: 0.2 }, motif: { geometry: 0.8, organic: 0.2, complexity: 0.3 }, arrangement: { order: 0.9, spacing: 0.95, direction: 0.5 } }, annotationSource: "assisted", confidence: "low", notes: "navy radial quadrant" }, tags: ["extended", "batch-2"] },
  { imageId: "080_556.png", title: "556", imageUrl: "/products-extra-fixed/080_556.png", annotation: { imageId: "080_556.png", firstOrder: { color: { warmth: 0.3, saturation: 0.9, lightness: 0.5 }, motif: { geometry: 0.9, organic: 0.6, complexity: 0.5 }, arrangement: { order: 0.7, spacing: 0.5, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "lime teal playful" }, tags: ["extended", "batch-2"] },
  { imageId: "081_557.jpg", title: "557", imageUrl: "/products-extra-fixed/081_557.jpg", annotation: { imageId: "081_557.jpg", firstOrder: { color: { warmth: 0.25, saturation: 0.4, lightness: 0.45 }, motif: { geometry: 0.7, organic: 0.1, complexity: 0.1 }, arrangement: { order: 0.95, spacing: 1.0, direction: 0.9 } }, annotationSource: "assisted", confidence: "low", notes: "vertical ribbed sage" }, tags: ["extended", "batch-2"] },
  { imageId: "082_558.jpg", title: "558", imageUrl: "/products-extra-fixed/082_558.jpg", annotation: { imageId: "082_558.jpg", firstOrder: { color: { warmth: 0.35, saturation: 0.05, lightness: 0.85 }, motif: { geometry: 0.8, organic: 0.1, complexity: 0.1 }, arrangement: { order: 0.95, spacing: 1.0, direction: 0.9 } }, annotationSource: "assisted", confidence: "low", notes: "off-white ribs" }, tags: ["extended", "batch-2"] },
  { imageId: "083_559.png", title: "559", imageUrl: "/products-extra-fixed/083_559.png", annotation: { imageId: "083_559.png", firstOrder: { color: { warmth: 0.35, saturation: 0.6, lightness: 0.3 }, motif: { geometry: 0.95, organic: 0.3, complexity: 0.7 }, arrangement: { order: 0.95, spacing: 0.8, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "olive grid spiral" }, tags: ["extended", "batch-2"] },
  { imageId: "084_560.png", title: "560", imageUrl: "/products-extra-fixed/084_560.png", annotation: { imageId: "084_560.png", firstOrder: { color: { warmth: 0.5, saturation: 0.05, lightness: 0.85 }, motif: { geometry: 0.0, organic: 1.0, complexity: 0.05 }, arrangement: { order: 0.3, spacing: 0.95, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "cream soft plush" }, tags: ["extended", "batch-2"] },
  { imageId: "085_561.jpg", title: "561", imageUrl: "/products-extra-fixed/085_561.jpg", annotation: { imageId: "085_561.jpg", firstOrder: { color: { warmth: 0.75, saturation: 0.6, lightness: 0.55 }, motif: { geometry: 0.95, organic: 0.4, complexity: 0.5 }, arrangement: { order: 0.9, spacing: 0.9, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "concentric rust cream" }, tags: ["extended", "batch-2"] },
  { imageId: "086_562.jpg", title: "562", imageUrl: "/products-extra-fixed/086_562.jpg", annotation: { imageId: "086_562.jpg", firstOrder: { color: { warmth: 0.85, saturation: 0.5, lightness: 0.4 }, motif: { geometry: 0.95, organic: 0.3, complexity: 0.2 }, arrangement: { order: 1.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "rust concentric" }, tags: ["extended", "batch-2"] },
  { imageId: "087_563.png", title: "563", imageUrl: "/products-extra-fixed/087_563.png", annotation: { imageId: "087_563.png", firstOrder: { color: { warmth: 0.25, saturation: 0.7, lightness: 0.15 }, motif: { geometry: 0.0, organic: 1.0, complexity: 0.05 }, arrangement: { order: 0.3, spacing: 0.95, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "deep forest plush" }, tags: ["extended", "batch-2"] },
  { imageId: "088_564.png", title: "564", imageUrl: "/products-extra-fixed/088_564.png", annotation: { imageId: "088_564.png", firstOrder: { color: { warmth: 0.25, saturation: 0.6, lightness: 0.3 }, motif: { geometry: 0.3, organic: 0.4, complexity: 0.25 }, arrangement: { order: 0.5, spacing: 0.9, direction: 0.9 } }, annotationSource: "assisted", confidence: "low", notes: "teal subtle vertical" }, tags: ["extended", "batch-2"] },
  { imageId: "089_565.jpg", title: "565", imageUrl: "/products-extra-fixed/089_565.jpg", annotation: { imageId: "089_565.jpg", firstOrder: { color: { warmth: 0.3, saturation: 0.3, lightness: 0.55 }, motif: { geometry: 0.8, organic: 0.3, complexity: 0.6 }, arrangement: { order: 0.6, spacing: 0.7, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "pixel gradient" }, tags: ["extended", "batch-2"] },
  { imageId: "090_566.png", title: "566", imageUrl: "/products-extra-fixed/090_566.png", annotation: { imageId: "090_566.png", firstOrder: { color: { warmth: 0.55, saturation: 0.15, lightness: 0.8 }, motif: { geometry: 0.6, organic: 0.3, complexity: 0.3 }, arrangement: { order: 0.8, spacing: 0.85, direction: 0.5 } }, annotationSource: "assisted", confidence: "low", notes: "cream braided" }, tags: ["extended", "batch-2"] },
  { imageId: "091_567.jpg", title: "567", imageUrl: "/products-extra-fixed/091_567.jpg", annotation: { imageId: "091_567.jpg", firstOrder: { color: { warmth: 0.3, saturation: 0.5, lightness: 0.7 }, motif: { geometry: 0.9, organic: 0.1, complexity: 0.3 }, arrangement: { order: 0.95, spacing: 0.8, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "oval concentric purple-teal" }, tags: ["extended", "batch-2"] },
  { imageId: "092_568.jpg", title: "568", imageUrl: "/products-extra-fixed/092_568.jpg", annotation: { imageId: "092_568.jpg", firstOrder: { color: { warmth: 0.2, saturation: 0.5, lightness: 0.6 }, motif: { geometry: 0.8, organic: 0.3, complexity: 0.8 }, arrangement: { order: 0.4, spacing: 0.3, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "circles cluster blue" }, tags: ["extended", "batch-2"] },
  { imageId: "093_569.jpg", title: "569", imageUrl: "/products-extra-fixed/093_569.jpg", annotation: { imageId: "093_569.jpg", firstOrder: { color: { warmth: 0.8, saturation: 0.3, lightness: 0.5 }, motif: { geometry: 0.2, organic: 0.1, complexity: 0.1 }, arrangement: { order: 0.9, spacing: 0.95, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid jute tan" }, tags: ["extended", "batch-2"] },
  { imageId: "094_570.png", title: "570", imageUrl: "/products-extra-fixed/094_570.png", annotation: { imageId: "094_570.png", firstOrder: { color: { warmth: 0.5, saturation: 0.15, lightness: 0.4 }, motif: { geometry: 0.1, organic: 0.1, complexity: 0.1 }, arrangement: { order: 0.9, spacing: 0.95, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid taupe nubby" }, tags: ["extended", "batch-2"] },
  { imageId: "095_571.png", title: "571", imageUrl: "/products-extra-fixed/095_571.png", annotation: { imageId: "095_571.png", firstOrder: { color: { warmth: 0.2, saturation: 0.3, lightness: 0.5 }, motif: { geometry: 0.2, organic: 0.1, complexity: 0.1 }, arrangement: { order: 0.9, spacing: 0.95, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid dusty-blue" }, tags: ["extended", "batch-2"] },
  { imageId: "096_572.png", title: "572", imageUrl: "/products-extra-fixed/096_572.png", annotation: { imageId: "096_572.png", firstOrder: { color: { warmth: 0.5, saturation: 0.1, lightness: 0.9 }, motif: { geometry: 0.3, organic: 0.1, complexity: 0.15 }, arrangement: { order: 0.7, spacing: 0.9, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "ivory subtle-grid" }, tags: ["extended", "batch-2"] },
  { imageId: "097_574.jpg", title: "574", imageUrl: "/products-extra-fixed/097_574.jpg", annotation: { imageId: "097_574.jpg", firstOrder: { color: { warmth: 0.6, saturation: 0.4, lightness: 0.35 }, motif: { geometry: 0.95, organic: 0.0, complexity: 0.3 }, arrangement: { order: 1.0, spacing: 0.85, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "grid brick-red" }, tags: ["extended", "batch-2"] },
  { imageId: "098_575.png", title: "575", imageUrl: "/products-extra-fixed/098_575.png", annotation: { imageId: "098_575.png", firstOrder: { color: { warmth: 0.5, saturation: 0.2, lightness: 0.85 }, motif: { geometry: 0.8, organic: 0.2, complexity: 0.5 }, arrangement: { order: 0.5, spacing: 0.6, direction: 0.7 } }, annotationSource: "assisted", confidence: "low", notes: "crosshatch diagonal" }, tags: ["extended", "batch-2"] },
  { imageId: "099_576.jpg", title: "576", imageUrl: "/products-extra-fixed/099_576.jpg", annotation: { imageId: "099_576.jpg", firstOrder: { color: { warmth: 0.35, saturation: 0.1, lightness: 0.35 }, motif: { geometry: 0.1, organic: 0.1, complexity: 0.1 }, arrangement: { order: 0.85, spacing: 0.95, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid charcoal" }, tags: ["extended", "batch-2"] },
  { imageId: "100_577.jpg", title: "577", imageUrl: "/products-extra-fixed/100_577.jpg", annotation: { imageId: "100_577.jpg", firstOrder: { color: { warmth: 0.4, saturation: 0.15, lightness: 0.85 }, motif: { geometry: 0.7, organic: 0.3, complexity: 0.4 }, arrangement: { order: 0.95, spacing: 0.8, direction: 0.5 } }, annotationSource: "assisted", confidence: "low", notes: "diamond lattice pale" }, tags: ["extended", "batch-2"] },
];
