import type { AnnotatedAssetRecord } from "./types";

/**
 * Batch 3 pre-annotations for extended assets (101–138).
 * All values are estimated drafts for the user to fine-tune after visual inspection.
 *
 * roleMap suitability scores [0–1]:
 *   probeSuitability       — good for early-round directional probing
 *   preferenceSuitability  — good for mid-round preference tracking
 *   convergenceSuitability — good for late-round convergence
 */
export const extendedPreannotationsBatch3: AnnotatedAssetRecord[] = [
  // ── GROUP A: Complex / warm-toned patterns ───────────────────────────────
  {
    imageId: "101_578.png",
    title: "578",
    imageUrl: "/products-extra-fixed/101_578.png",
    annotation: { imageId: "101_578.png", firstOrder: { color: { warmth: 0.70, saturation: 0.45, lightness: 0.55 }, motif: { geometry: 0.60, organic: 0.50, complexity: 0.70 }, arrangement: { order: 0.55, spacing: 0.40, direction: 0.50 } }, annotationSource: "assisted", confidence: "low", notes: "warm complex mixed pattern" },
    roleMap: { imageId: "101_578.png", roles: ["preference-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.60, preferenceSuitability: 0.78, convergenceSuitability: 0.48, brandRepresentativeness: 0.55 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "102_581.jpg",
    title: "581",
    imageUrl: "/products-extra-fixed/102_581.jpg",
    annotation: { imageId: "102_581.jpg", firstOrder: { color: { warmth: 0.25, saturation: 0.55, lightness: 0.40 }, motif: { geometry: 0.85, organic: 0.15, complexity: 0.55 }, arrangement: { order: 0.75, spacing: 0.45, direction: 0.60 } }, annotationSource: "assisted", confidence: "low", notes: "cool blue geometric ordered" },
    roleMap: { imageId: "102_581.jpg", roles: ["probe-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.82, preferenceSuitability: 0.45, convergenceSuitability: 0.38, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "103_582.jpg",
    title: "582",
    imageUrl: "/products-extra-fixed/103_582.jpg",
    annotation: { imageId: "103_582.jpg", firstOrder: { color: { warmth: 0.65, saturation: 0.30, lightness: 0.60 }, motif: { geometry: 0.20, organic: 0.80, complexity: 0.55 }, arrangement: { order: 0.30, spacing: 0.55, direction: 0.40 } }, annotationSource: "assisted", confidence: "low", notes: "warm organic flowing mid-tone" },
    roleMap: { imageId: "103_582.jpg", roles: ["preference-carrier"], strongSlots: ["motif", "color"], probeSuitability: 0.55, preferenceSuitability: 0.80, convergenceSuitability: 0.60, brandRepresentativeness: 0.52 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "104_583.jpg",
    title: "583",
    imageUrl: "/products-extra-fixed/104_583.jpg",
    annotation: { imageId: "104_583.jpg", firstOrder: { color: { warmth: 0.50, saturation: 0.10, lightness: 0.65 }, motif: { geometry: 0.60, organic: 0.20, complexity: 0.25 }, arrangement: { order: 0.85, spacing: 0.70, direction: 0.90 } }, annotationSource: "assisted", confidence: "low", notes: "neutral structured stripe high order" },
    roleMap: { imageId: "104_583.jpg", roles: ["convergence-carrier"], strongSlots: ["arrangement", "color"], probeSuitability: 0.50, preferenceSuitability: 0.62, convergenceSuitability: 0.80, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "105_584.jpg",
    title: "584",
    imageUrl: "/products-extra-fixed/105_584.jpg",
    annotation: { imageId: "105_584.jpg", firstOrder: { color: { warmth: 0.75, saturation: 0.50, lightness: 0.60 }, motif: { geometry: 0.70, organic: 0.35, complexity: 0.80 }, arrangement: { order: 0.65, spacing: 0.35, direction: 0.45 } }, annotationSource: "assisted", confidence: "low", notes: "warm gold complex all-over dense" },
    roleMap: { imageId: "105_584.jpg", roles: ["probe-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.80, preferenceSuitability: 0.55, convergenceSuitability: 0.35, brandRepresentativeness: 0.55 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "106_585.png",
    title: "585",
    imageUrl: "/products-extra-fixed/106_585.png",
    annotation: { imageId: "106_585.png", firstOrder: { color: { warmth: 0.30, saturation: 0.20, lightness: 0.15 }, motif: { geometry: 0.75, organic: 0.10, complexity: 0.20 }, arrangement: { order: 0.90, spacing: 0.65, direction: 0.90 } }, annotationSource: "assisted", confidence: "low", notes: "dark cool minimal geometric" },
    roleMap: { imageId: "106_585.png", roles: ["probe-carrier"], strongSlots: ["color", "arrangement"], probeSuitability: 0.85, preferenceSuitability: 0.42, convergenceSuitability: 0.40, brandRepresentativeness: 0.48 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "107_588.png",
    title: "588",
    imageUrl: "/products-extra-fixed/107_588.png",
    annotation: { imageId: "107_588.png", firstOrder: { color: { warmth: 0.55, saturation: 0.08, lightness: 0.88 }, motif: { geometry: 0.30, organic: 0.25, complexity: 0.15 }, arrangement: { order: 0.60, spacing: 0.75, direction: 0.50 } }, annotationSource: "assisted", confidence: "low", notes: "light cream subtle texture airy" },
    roleMap: { imageId: "107_588.png", roles: ["convergence-carrier"], strongSlots: ["color"], weakSlots: ["motif"], probeSuitability: 0.35, preferenceSuitability: 0.70, convergenceSuitability: 0.82, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "108_589.jpg",
    title: "589",
    imageUrl: "/products-extra-fixed/108_589.jpg",
    annotation: { imageId: "108_589.jpg", firstOrder: { color: { warmth: 0.85, saturation: 0.65, lightness: 0.45 }, motif: { geometry: 0.80, organic: 0.30, complexity: 0.75 }, arrangement: { order: 0.60, spacing: 0.35, direction: 0.50 } }, annotationSource: "assisted", confidence: "low", notes: "bold rust red complex geometric" },
    roleMap: { imageId: "108_589.jpg", roles: ["probe-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.88, preferenceSuitability: 0.45, convergenceSuitability: 0.28, brandRepresentativeness: 0.52 },
    tags: ["extended", "batch-3"],
  },

  // ── GROUP B: Structured / mid-range patterns ─────────────────────────────
  {
    imageId: "109_590.png",
    title: "590",
    imageUrl: "/products-extra-fixed/109_590.png",
    annotation: { imageId: "109_590.png", firstOrder: { color: { warmth: 0.35, saturation: 0.25, lightness: 0.55 }, motif: { geometry: 0.25, organic: 0.70, complexity: 0.50 }, arrangement: { order: 0.35, spacing: 0.55, direction: 0.60 } }, annotationSource: "assisted", confidence: "low", notes: "cool grey painterly flowing" },
    roleMap: { imageId: "109_590.png", roles: ["preference-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.52, preferenceSuitability: 0.80, convergenceSuitability: 0.62, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "110_591.png",
    title: "591",
    imageUrl: "/products-extra-fixed/110_591.png",
    annotation: { imageId: "110_591.png", firstOrder: { color: { warmth: 0.55, saturation: 0.15, lightness: 0.60 }, motif: { geometry: 0.40, organic: 0.45, complexity: 0.55 }, arrangement: { order: 0.50, spacing: 0.50, direction: 0.50 } }, annotationSource: "assisted", confidence: "low", notes: "neutral beige all-over moderate density" },
    roleMap: { imageId: "110_591.png", roles: ["convergence-carrier"], strongSlots: ["color"], probeSuitability: 0.40, preferenceSuitability: 0.68, convergenceSuitability: 0.78, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "111_592.png",
    title: "592",
    imageUrl: "/products-extra-fixed/111_592.png",
    annotation: { imageId: "111_592.png", firstOrder: { color: { warmth: 0.80, saturation: 0.60, lightness: 0.55 }, motif: { geometry: 0.90, organic: 0.15, complexity: 0.55 }, arrangement: { order: 0.70, spacing: 0.40, direction: 0.55 } }, annotationSource: "assisted", confidence: "low", notes: "bold warm orange geometric repeat" },
    roleMap: { imageId: "111_592.png", roles: ["probe-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.85, preferenceSuitability: 0.48, convergenceSuitability: 0.30, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "112_593.png",
    title: "593",
    imageUrl: "/products-extra-fixed/112_593.png",
    annotation: { imageId: "112_593.png", firstOrder: { color: { warmth: 0.20, saturation: 0.55, lightness: 0.40 }, motif: { geometry: 0.80, organic: 0.10, complexity: 0.40 }, arrangement: { order: 0.80, spacing: 0.55, direction: 0.70 } }, annotationSource: "assisted", confidence: "low", notes: "cool teal structured ordered" },
    roleMap: { imageId: "112_593.png", roles: ["probe-carrier"], strongSlots: ["color", "arrangement"], probeSuitability: 0.82, preferenceSuitability: 0.48, convergenceSuitability: 0.40, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "113_594.png",
    title: "594",
    imageUrl: "/products-extra-fixed/113_594.png",
    annotation: { imageId: "113_594.png", firstOrder: { color: { warmth: 0.55, saturation: 0.12, lightness: 0.72 }, motif: { geometry: 0.20, organic: 0.65, complexity: 0.40 }, arrangement: { order: 0.35, spacing: 0.60, direction: 0.40 } }, annotationSource: "assisted", confidence: "low", notes: "light neutral organic scattered" },
    roleMap: { imageId: "113_594.png", roles: ["preference-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.42, preferenceSuitability: 0.80, convergenceSuitability: 0.70, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "114_595.png",
    title: "595",
    imageUrl: "/products-extra-fixed/114_595.png",
    annotation: { imageId: "114_595.png", firstOrder: { color: { warmth: 0.45, saturation: 0.35, lightness: 0.30 }, motif: { geometry: 0.55, organic: 0.45, complexity: 0.75 }, arrangement: { order: 0.55, spacing: 0.35, direction: 0.45 } }, annotationSource: "assisted", confidence: "low", notes: "dark complex traditional dense" },
    roleMap: { imageId: "114_595.png", roles: ["preference-carrier"], strongSlots: ["motif", "color"], probeSuitability: 0.65, preferenceSuitability: 0.78, convergenceSuitability: 0.50, brandRepresentativeness: 0.55 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "115_596.jpg",
    title: "596",
    imageUrl: "/products-extra-fixed/115_596.jpg",
    annotation: { imageId: "115_596.jpg", firstOrder: { color: { warmth: 0.50, saturation: 0.08, lightness: 0.60 }, motif: { geometry: 0.65, organic: 0.10, complexity: 0.15 }, arrangement: { order: 0.95, spacing: 0.70, direction: 0.95 } }, annotationSource: "assisted", confidence: "low", notes: "neutral stripe very ordered convergent" },
    roleMap: { imageId: "115_596.jpg", roles: ["convergence-carrier"], strongSlots: ["arrangement"], weakSlots: ["motif"], probeSuitability: 0.45, preferenceSuitability: 0.60, convergenceSuitability: 0.85, brandRepresentativeness: 0.48 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "116_597.jpg",
    title: "597",
    imageUrl: "/products-extra-fixed/116_597.jpg",
    annotation: { imageId: "116_597.jpg", firstOrder: { color: { warmth: 0.70, saturation: 0.45, lightness: 0.65 }, motif: { geometry: 0.50, organic: 0.60, complexity: 0.65 }, arrangement: { order: 0.40, spacing: 0.45, direction: 0.55 } }, annotationSource: "assisted", confidence: "low", notes: "warm playful mixed motif energy" },
    roleMap: { imageId: "116_597.jpg", roles: ["probe-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.78, preferenceSuitability: 0.55, convergenceSuitability: 0.30, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },

  // ── GROUP C: Light / cool geometric ──────────────────────────────────────
  {
    imageId: "117_598.jpg",
    title: "598",
    imageUrl: "/products-extra-fixed/117_598.jpg",
    annotation: { imageId: "117_598.jpg", firstOrder: { color: { warmth: 0.30, saturation: 0.10, lightness: 0.82 }, motif: { geometry: 0.80, organic: 0.05, complexity: 0.20 }, arrangement: { order: 0.90, spacing: 0.75, direction: 0.90 } }, annotationSource: "assisted", confidence: "low", notes: "cool light geometric grid ordered" },
    roleMap: { imageId: "117_598.jpg", roles: ["probe-carrier"], strongSlots: ["arrangement", "color"], probeSuitability: 0.82, preferenceSuitability: 0.50, convergenceSuitability: 0.55, brandRepresentativeness: 0.48 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "118_599.jpg",
    title: "599",
    imageUrl: "/products-extra-fixed/118_599.jpg",
    annotation: { imageId: "118_599.jpg", firstOrder: { color: { warmth: 0.65, saturation: 0.35, lightness: 0.45 }, motif: { geometry: 0.50, organic: 0.35, complexity: 0.70 }, arrangement: { order: 0.65, spacing: 0.40, direction: 0.55 } }, annotationSource: "assisted", confidence: "low", notes: "warm earth heritage dense" },
    roleMap: { imageId: "118_599.jpg", roles: ["convergence-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.48, preferenceSuitability: 0.72, convergenceSuitability: 0.80, brandRepresentativeness: 0.58 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "119_600.jpg",
    title: "600",
    imageUrl: "/products-extra-fixed/119_600.jpg",
    annotation: { imageId: "119_600.jpg", firstOrder: { color: { warmth: 0.50, saturation: 0.10, lightness: 0.78 }, motif: { geometry: 0.15, organic: 0.60, complexity: 0.35 }, arrangement: { order: 0.30, spacing: 0.65, direction: 0.35 } }, annotationSource: "assisted", confidence: "low", notes: "light airy abstract open" },
    roleMap: { imageId: "119_600.jpg", roles: ["preference-carrier", "convergence-carrier"], strongSlots: ["color", "impression"], probeSuitability: 0.38, preferenceSuitability: 0.80, convergenceSuitability: 0.75, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "120_601.png",
    title: "601",
    imageUrl: "/products-extra-fixed/120_601.png",
    annotation: { imageId: "120_601.png", firstOrder: { color: { warmth: 0.20, saturation: 0.60, lightness: 0.45 }, motif: { geometry: 0.90, organic: 0.10, complexity: 0.45 }, arrangement: { order: 0.80, spacing: 0.50, direction: 0.55 } }, annotationSource: "assisted", confidence: "low", notes: "cool bold geometric saturated" },
    roleMap: { imageId: "120_601.png", roles: ["probe-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.85, preferenceSuitability: 0.45, convergenceSuitability: 0.32, brandRepresentativeness: 0.50 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "121_603.jpg",
    title: "603",
    imageUrl: "/products-extra-fixed/121_603.jpg",
    annotation: { imageId: "121_603.jpg", firstOrder: { color: { warmth: 0.55, saturation: 0.40, lightness: 0.50 }, motif: { geometry: 0.45, organic: 0.55, complexity: 0.75 }, arrangement: { order: 0.45, spacing: 0.40, direction: 0.40 } }, annotationSource: "assisted", confidence: "low", notes: "complex abstract multi-layered" },
    roleMap: { imageId: "121_603.jpg", roles: ["preference-carrier"], strongSlots: ["motif", "color"], probeSuitability: 0.62, preferenceSuitability: 0.78, convergenceSuitability: 0.45, brandRepresentativeness: 0.55 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "122_604.jpg",
    title: "604",
    imageUrl: "/products-extra-fixed/122_604.jpg",
    annotation: { imageId: "122_604.jpg", firstOrder: { color: { warmth: 0.70, saturation: 0.50, lightness: 0.35 }, motif: { geometry: 0.85, organic: 0.20, complexity: 0.55 }, arrangement: { order: 0.65, spacing: 0.40, direction: 0.50 } }, annotationSource: "assisted", confidence: "low", notes: "warm dark bold graphic structured" },
    roleMap: { imageId: "122_604.jpg", roles: ["probe-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.83, preferenceSuitability: 0.52, convergenceSuitability: 0.32, brandRepresentativeness: 0.52 },
    tags: ["extended", "batch-3"],
  },

  // ── GROUP D: Traditional / heritage patterns ──────────────────────────────
  {
    imageId: "123_917.png",
    title: "917",
    imageUrl: "/products-extra-fixed/123_917.png",
    annotation: { imageId: "123_917.png", firstOrder: { color: { warmth: 0.55, saturation: 0.20, lightness: 0.55 }, motif: { geometry: 0.65, organic: 0.30, complexity: 0.60 }, arrangement: { order: 0.75, spacing: 0.50, direction: 0.60 } }, annotationSource: "assisted", confidence: "low", notes: "traditional medallion neutral heritage" },
    roleMap: { imageId: "123_917.png", roles: ["convergence-carrier"], strongSlots: ["arrangement", "style"], probeSuitability: 0.42, preferenceSuitability: 0.68, convergenceSuitability: 0.82, brandRepresentativeness: 0.60 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "124_461.png",
    title: "461",
    imageUrl: "/products-extra-fixed/124_461.png",
    annotation: { imageId: "124_461.png", firstOrder: { color: { warmth: 0.30, saturation: 0.30, lightness: 0.50 }, motif: { geometry: 0.80, organic: 0.10, complexity: 0.40 }, arrangement: { order: 0.85, spacing: 0.60, direction: 0.90 } }, annotationSource: "assisted", confidence: "low", notes: "cool border structured geometric" },
    roleMap: { imageId: "124_461.png", roles: ["probe-carrier"], strongSlots: ["arrangement", "color"], probeSuitability: 0.80, preferenceSuitability: 0.50, convergenceSuitability: 0.52, brandRepresentativeness: 0.55 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "125_473.png",
    title: "473",
    imageUrl: "/products-extra-fixed/125_473.png",
    annotation: { imageId: "125_473.png", firstOrder: { color: { warmth: 0.65, saturation: 0.30, lightness: 0.58 }, motif: { geometry: 0.25, organic: 0.80, complexity: 0.55 }, arrangement: { order: 0.30, spacing: 0.55, direction: 0.45 } }, annotationSource: "assisted", confidence: "low", notes: "warm organic flowing mid-density" },
    roleMap: { imageId: "125_473.png", roles: ["preference-carrier"], strongSlots: ["motif", "color"], probeSuitability: 0.55, preferenceSuitability: 0.80, convergenceSuitability: 0.60, brandRepresentativeness: 0.52 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "126_47.png",
    title: "47",
    imageUrl: "/products-extra-fixed/126_47.png",
    annotation: { imageId: "126_47.png", firstOrder: { color: { warmth: 0.40, saturation: 0.40, lightness: 0.20 }, motif: { geometry: 0.70, organic: 0.30, complexity: 0.80 }, arrangement: { order: 0.60, spacing: 0.30, direction: 0.50 } }, annotationSource: "assisted", confidence: "low", notes: "dark dense complex high contrast" },
    roleMap: { imageId: "126_47.png", roles: ["probe-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.85, preferenceSuitability: 0.45, convergenceSuitability: 0.28, brandRepresentativeness: 0.55 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "127_56.png",
    title: "56",
    imageUrl: "/products-extra-fixed/127_56.png",
    annotation: { imageId: "127_56.png", firstOrder: { color: { warmth: 0.50, saturation: 0.05, lightness: 0.90 }, motif: { geometry: 0.10, organic: 0.20, complexity: 0.08 }, arrangement: { order: 0.10, spacing: 0.95, direction: 0.10 } }, annotationSource: "assisted", confidence: "low", notes: "light minimal solid-adjacent very calm" },
    roleMap: { imageId: "127_56.png", roles: ["convergence-carrier"], strongSlots: ["color"], weakSlots: ["motif"], probeSuitability: 0.30, preferenceSuitability: 0.65, convergenceSuitability: 0.85, brandRepresentativeness: 0.45 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "128_57.png",
    title: "57",
    imageUrl: "/products-extra-fixed/128_57.png",
    annotation: { imageId: "128_57.png", firstOrder: { color: { warmth: 0.65, saturation: 0.30, lightness: 0.50 }, motif: { geometry: 0.50, organic: 0.45, complexity: 0.60 }, arrangement: { order: 0.55, spacing: 0.45, direction: 0.50 } }, annotationSource: "assisted", confidence: "low", notes: "warm medium traditional mixed" },
    roleMap: { imageId: "128_57.png", roles: ["preference-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.58, preferenceSuitability: 0.78, convergenceSuitability: 0.55, brandRepresentativeness: 0.55 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "129_72.png",
    title: "72",
    imageUrl: "/products-extra-fixed/129_72.png",
    annotation: { imageId: "129_72.png", firstOrder: { color: { warmth: 0.25, saturation: 0.35, lightness: 0.45 }, motif: { geometry: 0.85, organic: 0.10, complexity: 0.35 }, arrangement: { order: 0.85, spacing: 0.55, direction: 0.80 } }, annotationSource: "assisted", confidence: "low", notes: "cool structured geometric crisp" },
    roleMap: { imageId: "129_72.png", roles: ["probe-carrier"], strongSlots: ["color", "arrangement"], probeSuitability: 0.82, preferenceSuitability: 0.48, convergenceSuitability: 0.42, brandRepresentativeness: 0.52 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "130_73.png",
    title: "73",
    imageUrl: "/products-extra-fixed/130_73.png",
    annotation: { imageId: "130_73.png", firstOrder: { color: { warmth: 0.50, saturation: 0.12, lightness: 0.65 }, motif: { geometry: 0.30, organic: 0.50, complexity: 0.35 }, arrangement: { order: 0.45, spacing: 0.60, direction: 0.40 } }, annotationSource: "assisted", confidence: "low", notes: "neutral soft subtle open" },
    roleMap: { imageId: "130_73.png", roles: ["convergence-carrier"], strongSlots: ["color"], probeSuitability: 0.35, preferenceSuitability: 0.70, convergenceSuitability: 0.82, brandRepresentativeness: 0.48 },
    tags: ["extended", "batch-3"],
  },

  // ── GROUP E: Bold modern / older catalog items ────────────────────────────
  {
    imageId: "131_13.png",
    title: "13",
    imageUrl: "/products-extra-fixed/131_13.png",
    annotation: { imageId: "131_13.png", firstOrder: { color: { warmth: 0.70, saturation: 0.40, lightness: 0.48 }, motif: { geometry: 0.55, organic: 0.45, complexity: 0.65 }, arrangement: { order: 0.60, spacing: 0.45, direction: 0.55 } }, annotationSource: "assisted", confidence: "low", notes: "warm heritage complex artisanal" },
    roleMap: { imageId: "131_13.png", roles: ["preference-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.58, preferenceSuitability: 0.78, convergenceSuitability: 0.55, brandRepresentativeness: 0.60 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "132_474.png",
    title: "474",
    imageUrl: "/products-extra-fixed/132_474.png",
    annotation: { imageId: "132_474.png", firstOrder: { color: { warmth: 0.20, saturation: 0.60, lightness: 0.40 }, motif: { geometry: 0.90, organic: 0.10, complexity: 0.50 }, arrangement: { order: 0.80, spacing: 0.45, direction: 0.65 } }, annotationSource: "assisted", confidence: "low", notes: "cool bold geometric saturated directional" },
    roleMap: { imageId: "132_474.png", roles: ["probe-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.85, preferenceSuitability: 0.45, convergenceSuitability: 0.30, brandRepresentativeness: 0.52 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "133_14.png",
    title: "14",
    imageUrl: "/products-extra-fixed/133_14.png",
    annotation: { imageId: "133_14.png", firstOrder: { color: { warmth: 0.75, saturation: 0.55, lightness: 0.55 }, motif: { geometry: 0.75, organic: 0.25, complexity: 0.65 }, arrangement: { order: 0.65, spacing: 0.40, direction: 0.55 } }, annotationSource: "assisted", confidence: "low", notes: "warm vibrant energetic bold" },
    roleMap: { imageId: "133_14.png", roles: ["probe-carrier"], strongSlots: ["color", "motif"], probeSuitability: 0.85, preferenceSuitability: 0.48, convergenceSuitability: 0.28, brandRepresentativeness: 0.55 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "134_7.png",
    title: "7",
    imageUrl: "/products-extra-fixed/134_7.png",
    annotation: { imageId: "134_7.png", firstOrder: { color: { warmth: 0.50, saturation: 0.08, lightness: 0.80 }, motif: { geometry: 0.15, organic: 0.15, complexity: 0.10 }, arrangement: { order: 0.25, spacing: 0.90, direction: 0.20 } }, annotationSource: "assisted", confidence: "low", notes: "light neutral minimal very open" },
    roleMap: { imageId: "134_7.png", roles: ["convergence-carrier"], strongSlots: ["color"], weakSlots: ["motif", "arrangement"], probeSuitability: 0.28, preferenceSuitability: 0.62, convergenceSuitability: 0.85, brandRepresentativeness: 0.45 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "135_15.png",
    title: "15",
    imageUrl: "/products-extra-fixed/135_15.png",
    annotation: { imageId: "135_15.png", firstOrder: { color: { warmth: 0.65, saturation: 0.25, lightness: 0.62 }, motif: { geometry: 0.20, organic: 0.80, complexity: 0.50 }, arrangement: { order: 0.28, spacing: 0.55, direction: 0.35 } }, annotationSource: "assisted", confidence: "low", notes: "warm organic artisanal flowing" },
    roleMap: { imageId: "135_15.png", roles: ["preference-carrier"], strongSlots: ["motif", "color"], probeSuitability: 0.55, preferenceSuitability: 0.82, convergenceSuitability: 0.58, brandRepresentativeness: 0.58 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "136_20.png",
    title: "20",
    imageUrl: "/products-extra-fixed/136_20.png",
    annotation: { imageId: "136_20.png", firstOrder: { color: { warmth: 0.68, saturation: 0.40, lightness: 0.50 }, motif: { geometry: 0.45, organic: 0.55, complexity: 0.75 }, arrangement: { order: 0.50, spacing: 0.40, direction: 0.45 } }, annotationSource: "assisted", confidence: "low", notes: "warm complex all-over mid-density" },
    roleMap: { imageId: "136_20.png", roles: ["preference-carrier"], strongSlots: ["motif", "color"], probeSuitability: 0.60, preferenceSuitability: 0.80, convergenceSuitability: 0.48, brandRepresentativeness: 0.58 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "137_22.png",
    title: "22",
    imageUrl: "/products-extra-fixed/137_22.png",
    annotation: { imageId: "137_22.png", firstOrder: { color: { warmth: 0.35, saturation: 0.25, lightness: 0.22 }, motif: { geometry: 0.80, organic: 0.15, complexity: 0.45 }, arrangement: { order: 0.85, spacing: 0.55, direction: 0.80 } }, annotationSource: "assisted", confidence: "low", notes: "dark bold structured high-contrast" },
    roleMap: { imageId: "137_22.png", roles: ["probe-carrier"], strongSlots: ["color", "arrangement"], probeSuitability: 0.85, preferenceSuitability: 0.45, convergenceSuitability: 0.35, brandRepresentativeness: 0.52 },
    tags: ["extended", "batch-3"],
  },
  {
    imageId: "138_23.png",
    title: "23",
    imageUrl: "/products-extra-fixed/138_23.png",
    annotation: { imageId: "138_23.png", firstOrder: { color: { warmth: 0.50, saturation: 0.12, lightness: 0.75 }, motif: { geometry: 0.75, organic: 0.10, complexity: 0.25 }, arrangement: { order: 0.85, spacing: 0.70, direction: 0.85 } }, annotationSource: "assisted", confidence: "low", notes: "light geometric simple ordered" },
    roleMap: { imageId: "138_23.png", roles: ["probe-carrier"], strongSlots: ["arrangement", "motif"], probeSuitability: 0.78, preferenceSuitability: 0.52, convergenceSuitability: 0.55, brandRepresentativeness: 0.48 },
    tags: ["extended", "batch-3"],
  },
];
