import type { AnnotatedAssetRecord } from "./types";

/**
 * Batch 1 simplified pre-annotations for extended assets.
 * Goal: expand matching space, not final semantic truth.
 */
export const extendedPreannotationsBatch1: AnnotatedAssetRecord[] = [
  { imageId: "051_514.png", title: "514", imageUrl: "/products-extra-fixed/051_514.png", annotation: { imageId: "051_514.png", firstOrder: { color: { warmth: 0.7, saturation: 0.4, lightness: 0.7 }, motif: { geometry: 1.0, organic: 0.1, complexity: 0.5 }, arrangement: { order: 0.7, spacing: 0.6, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "patchwork gold-white" }, tags: ["extended", "batch-1"] },
  { imageId: "052_515.jpg", title: "515", imageUrl: "/products-extra-fixed/052_515.jpg", annotation: { imageId: "052_515.jpg", firstOrder: { color: { warmth: 0.2, saturation: 0.6, lightness: 0.4 }, motif: { geometry: 1.0, organic: 0.1, complexity: 0.5 }, arrangement: { order: 0.7, spacing: 0.6, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "patchwork indigo" }, tags: ["extended", "batch-1"] },
  { imageId: "053_518.jpg", title: "518", imageUrl: "/products-extra-fixed/053_518.jpg", annotation: { imageId: "053_518.jpg", firstOrder: { color: { warmth: 0.5, saturation: 0.0, lightness: 0.6 }, motif: { geometry: 0.3, organic: 0.8, complexity: 0.4 }, arrangement: { order: 0.9, spacing: 0.7, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "border pebbles" }, tags: ["extended", "batch-1"] },
  { imageId: "054_520.png", title: "520", imageUrl: "/products-extra-fixed/054_520.png", annotation: { imageId: "054_520.png", firstOrder: { color: { warmth: 0.5, saturation: 0.0, lightness: 0.5 }, motif: { geometry: 1.0, organic: 0.0, complexity: 0.2 }, arrangement: { order: 1.0, spacing: 1.0, direction: 1.0 } }, annotationSource: "assisted", confidence: "low", notes: "grid minimal" }, tags: ["extended", "batch-1"] },
  { imageId: "055_521.jpg", title: "521", imageUrl: "/products-extra-fixed/055_521.jpg", annotation: { imageId: "055_521.jpg", firstOrder: { color: { warmth: 0.6, saturation: 0.2, lightness: 0.6 }, motif: { geometry: 0.4, organic: 0.9, complexity: 0.5 }, arrangement: { order: 0.3, spacing: 0.5, direction: 0.7 } }, annotationSource: "assisted", confidence: "low", notes: "botanical branches" }, tags: ["extended", "batch-1"] },
  { imageId: "056_524.jpg", title: "524", imageUrl: "/products-extra-fixed/056_524.jpg", annotation: { imageId: "056_524.jpg", firstOrder: { color: { warmth: 0.4, saturation: 0.05, lightness: 0.95 }, motif: { geometry: 0.0, organic: 0.2, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid mint" }, tags: ["extended", "batch-1"] },
  { imageId: "057_525.jpg", title: "525", imageUrl: "/products-extra-fixed/057_525.jpg", annotation: { imageId: "057_525.jpg", firstOrder: { color: { warmth: 0.5, saturation: 0.0, lightness: 0.95 }, motif: { geometry: 0.0, organic: 0.3, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid shag-white" }, tags: ["extended", "batch-1"] },
  { imageId: "058_526.jpg", title: "526", imageUrl: "/products-extra-fixed/058_526.jpg", annotation: { imageId: "058_526.jpg", firstOrder: { color: { warmth: 0.5, saturation: 0.05, lightness: 0.9 }, motif: { geometry: 0.0, organic: 0.2, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid cream" }, tags: ["extended", "batch-1"] },
  { imageId: "059_528.jpg", title: "528", imageUrl: "/products-extra-fixed/059_528.jpg", annotation: { imageId: "059_528.jpg", firstOrder: { color: { warmth: 0.5, saturation: 0.0, lightness: 0.05 }, motif: { geometry: 0.0, organic: 0.2, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid black" }, tags: ["extended", "batch-1"] },
  { imageId: "060_529.jpg", title: "529", imageUrl: "/products-extra-fixed/060_529.jpg", annotation: { imageId: "060_529.jpg", firstOrder: { color: { warmth: 0.7, saturation: 0.15, lightness: 0.75 }, motif: { geometry: 0.0, organic: 0.3, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid beige" }, tags: ["extended", "batch-1"] },
  { imageId: "061_530.jpg", title: "530", imageUrl: "/products-extra-fixed/061_530.jpg", annotation: { imageId: "061_530.jpg", firstOrder: { color: { warmth: 0.75, saturation: 0.25, lightness: 0.6 }, motif: { geometry: 0.0, organic: 0.3, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid tan" }, tags: ["extended", "batch-1"] },
  { imageId: "062_531.jpg", title: "531", imageUrl: "/products-extra-fixed/062_531.jpg", annotation: { imageId: "062_531.jpg", firstOrder: { color: { warmth: 0.3, saturation: 0.3, lightness: 0.25 }, motif: { geometry: 0.0, organic: 0.3, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid forest" }, tags: ["extended", "batch-1"] },
  { imageId: "063_532.jpg", title: "532", imageUrl: "/products-extra-fixed/063_532.jpg", annotation: { imageId: "063_532.jpg", firstOrder: { color: { warmth: 0.5, saturation: 0.2, lightness: 0.3 }, motif: { geometry: 0.0, organic: 0.3, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid olive" }, tags: ["extended", "batch-1"] },
  { imageId: "064_533.jpg", title: "533", imageUrl: "/products-extra-fixed/064_533.jpg", annotation: { imageId: "064_533.jpg", firstOrder: { color: { warmth: 0.4, saturation: 0.05, lightness: 0.85 }, motif: { geometry: 0.0, organic: 0.3, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid silver" }, tags: ["extended", "batch-1"] },
  { imageId: "065_534.jpg", title: "534", imageUrl: "/products-extra-fixed/065_534.jpg", annotation: { imageId: "065_534.jpg", firstOrder: { color: { warmth: 0.5, saturation: 0.0, lightness: 0.95 }, motif: { geometry: 0.0, organic: 0.1, complexity: 0.05 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid off-white" }, tags: ["extended", "batch-1"] },
  { imageId: "066_535.jpg", title: "535", imageUrl: "/products-extra-fixed/066_535.jpg", annotation: { imageId: "066_535.jpg", firstOrder: { color: { warmth: 0.35, saturation: 0.15, lightness: 0.5 }, motif: { geometry: 0.0, organic: 0.3, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid sage" }, tags: ["extended", "batch-1"] },
  { imageId: "067_536.jpg", title: "536", imageUrl: "/products-extra-fixed/067_536.jpg", annotation: { imageId: "067_536.jpg", firstOrder: { color: { warmth: 0.6, saturation: 0.15, lightness: 0.65 }, motif: { geometry: 0.0, organic: 0.3, complexity: 0.15 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid oatmeal" }, tags: ["extended", "batch-1"] },
  { imageId: "068_537.jpg", title: "537", imageUrl: "/products-extra-fixed/068_537.jpg", annotation: { imageId: "068_537.jpg", firstOrder: { color: { warmth: 0.6, saturation: 0.1, lightness: 0.85 }, motif: { geometry: 0.0, organic: 0.2, complexity: 0.1 }, arrangement: { order: 0.0, spacing: 1.0, direction: 0.0 } }, annotationSource: "assisted", confidence: "low", notes: "solid ivory" }, tags: ["extended", "batch-1"] },
  { imageId: "069_543.png", title: "543", imageUrl: "/products-extra-fixed/069_543.png", annotation: { imageId: "069_543.png", firstOrder: { color: { warmth: 0.8, saturation: 0.5, lightness: 0.6 }, motif: { geometry: 0.8, organic: 0.1, complexity: 0.2 }, arrangement: { order: 0.9, spacing: 0.9, direction: 0.5 } }, annotationSource: "assisted", confidence: "low", notes: "border gold woven" }, tags: ["extended", "batch-1"] },
  { imageId: "070_544.jpg", title: "544", imageUrl: "/products-extra-fixed/070_544.jpg", annotation: { imageId: "070_544.jpg", firstOrder: { color: { warmth: 0.7, saturation: 0.35, lightness: 0.5 }, motif: { geometry: 0.7, organic: 0.2, complexity: 0.3 }, arrangement: { order: 0.8, spacing: 0.8, direction: 0.7 } }, annotationSource: "assisted", confidence: "low", notes: "sisal diagonal-weave" }, tags: ["extended", "batch-1"] },
];
